### ISSUE TITLE
Function without return can continue execution beyond the end

### ISSUE THREAD

**Issue by roblabla** [sagiegurari/duckscript#110]
**Describe the bug**
I am *extremely confused* by this bug. It appears that, under certain (presently unknown) conditions, a function may continue executing beyond the `end` of the function, potentially causing an infinite loop.  What's especially confusing is that even *comments* seem to influence the outcome 😕.

**To Reproduce**
Run the cargo-make reproducer found in the code sample below.

**Code Sample**
```toml
[tasks.repro]
script_runner = "@duckscript"
script = ['''
#
#
#
#
#

function apply_patches
    patches = glob_array ${CARGO_MAKE_WORKING_DIRECTORY}/*.patch
    patches = array_join ${patches} " "
    backslashes = set "\\"
    backslashes = concat ${backslashes} ${backslashes}
    patches = replace ${patches} "\\" ${backslashes}
    set_env GIT_COMMITTER_NAME patchsystem
    set_env GIT_COMMITTER_EMAIL patchsystem
    echo %{patches}
end

apply_patches
''']
```
