### ISSUE TITLE
Question: Remove directory if present?

### ISSUE THREAD

**Issue by Kreyren** [sagiegurari/duckscript#147]
I have this task in cargo-make:

```toml
[env]
BUILD = "build"

[tasks.clean]
description = "Remove temporary directories"
script = '''
#!/bin/sh
[ ! -d "${BUILD}" ] || rm -r "${BUILD}"
'''
```

How can i translate it to duckscript? It seems to not have conditionals?
