### ISSUE TITLE
Support array spread in exec

### ISSUE THREAD

**Issue by dovahcrow** [sagiegurari/duckscript#354]
### Feature Description

This is similar to #133 but came from cargo-make and is for array:
When using `cargo-make`, additional parameters are stored in `${@}`, like other runners.
However, in duckscript, `${@}` is an array, making it impossible to pass to `exec`.

### Describe The Solution You'd Like

Maybe add a new syntax to spread the array?

### Code Sample

```
/// paste code here
exec cargo run --release -- ${@}
```
Or any new syntax makes the above work.

**Comment by dovahcrow** [comment]
Yeah `array_join` then `spread` is an option I haven't think of (still thinking in strong typing lol) 

Anyway, you can close the issue if you feel a new syntax is unnecessary.

**Comment by sagiegurari** [comment]
just saw the edit, can you tell me what you tried and what you saw?

**Comment by dovahcrow** [comment]
@sagiegurari I tried:
```toml
[tasks.release]
script = """
files = array_join ${@} " "
exec --fail-on-error tar -cf release.tar must_have.sh %{files}
"""
script_runner = "@duckscript"
```

`cargo make release abc` worked but `cargo make release` won't.
